name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read

jobs:
  # Run shared tests and security checks
  test-and-security:
    uses: ./.github/workflows/test-and-security.yml

  # PR-specific checks can be added here in the future
  # For example:
  # pr-specific-checks:
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check PR title
  #     - name: Check commit messages
  #     - name: etc...